services:
  - type: web
    name: voice-assistant
    env: python
    buildCommand: pip install -e .
    startCommand: python run.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0 